# Site settings
title: Welcome to Operation Spark and Positive Space!
email: scanderson515@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty

# Server Settings
port: 8080
host: 0.0.0.0
